TimeSeries/PublicApis/R/FlowDurationCurve/AQTS-FDC.r
Now they are multiline, to adapt to larger location names a bit better.
=> PF-67 Fixed the flow duration curve labels

TimeSeries/PublicApis/TableauConnector/AQDC_DataPhase2.js, TimeSeries/PublicApis/TableauConnector/AQUARIUSConnector2.html, TimeSeries/PublicApis/TableauConnector/Readme.md
1) Added elevation and UTC offset to Location table
2) Added TimeSeries table
3) Updated the Readme
=> PF-70 Added TimeSeries table and more Location columns

TimeSeries/PublicApis/Python/WindRose/timeseries_client.py, TimeSeries/PublicApis/Python/timeseries_client.py, TimeSeries/PublicApis/R/ExtremeValueAnalysis/timeseries_client.R, TimeSeries/PublicApis/R/FloodFrequencyAnalysis/timeseries_client.R, TimeSeries/PublicApis/R/FlowDurationCurve/timeseries_client.R, TimeSeries/PublicApis/R/IntensityDurationFrequency/timeseries_client.R, TimeSeries/PublicApis/R/ShinyFlowDurationCurve/timeseries_client.R, TimeSeries/PublicApis/R/WindRose/timeseries_client.R, TimeSeries/PublicApis/R/timeseries_client.R
This common approach for repeated API calls will help curious data scientists get their data more quickly.
=> PF-77 Added batch request support to R and Python wrappers

TimeSeries/PublicApis/R/ExtremeValueAnalysis/timeseries_client.R, TimeSeries/PublicApis/R/FloodFrequencyAnalysis/timeseries_client.R, TimeSeries/PublicApis/R/FlowDurationCurve/timeseries_client.R, TimeSeries/PublicApis/R/IntensityDurationFrequency/timeseries_client.R, TimeSeries/PublicApis/R/ShinyFlowDurationCurve/timeseries_client.R, TimeSeries/PublicApis/R/WindRose/timeseries_client.R, TimeSeries/PublicApis/R/timeseries_client.R
It's rather embarrassing that I spent an entire day tracking down the required magic of `rbind_pages(responseBatches)`.
=> PF-77 Fixed the sendBatchRequests() method to correctly combine the paginated JSON results

TimeSeries/PublicApis/R/ExtremeValueAnalysis/timeseries_client.R, TimeSeries/PublicApis/R/FloodFrequencyAnalysis/timeseries_client.R, TimeSeries/PublicApis/R/FlowDurationCurve/timeseries_client.R, TimeSeries/PublicApis/R/IntensityDurationFrequency/timeseries_client.R, TimeSeries/PublicApis/R/ShinyFlowDurationCurve/timeseries_client.R, TimeSeries/PublicApis/R/WindRose/timeseries_client.R, TimeSeries/PublicApis/R/timeseries_client.R
1) Added getFieldVisits() and getRatings() methods
=> PF-77 Improved R wrapper

TimeSeries/PublicApis/FieldDataPlugins/PluginTester/PluginTester.csproj
Now it can load the 64-bit framework assembly.
=> PF-99 Fix the Release build of the PluginTester.exe

TimeSeries/PublicApis/R/Readme.md, TimeSeries/PublicApis/R/timeseries_client.R
Not all of the methods are working yet, but many are.
=> PF-105 Updated the main wrapper to enable connections to 3.X app servers

Samples/DotNetSdk/DotNetSdkExamples.sln, Samples/DotNetSdk/ObservationValidator/App.config, Samples/DotNetSdk/ObservationValidator/ComparisonSymbol.cs, Samples/DotNetSdk/ObservationValidator/Context.cs, Samples/DotNetSdk/ObservationValidator/DoubleHelper.cs, Samples/DotNetSdk/ObservationValidator/FilePathHelper.cs, Samples/DotNetSdk/ObservationValidator/LastRunTimeKeeper.cs, Samples/DotNetSdk/ObservationValidator/ObservationValidator.csproj, Samples/DotNetSdk/ObservationValidator/Program.cs, Samples/DotNetSdk/ObservationValidator/Properties/AssemblyInfo.cs, Samples/DotNetSdk/ObservationValidator/README.md, Samples/DotNetSdk/ObservationValidator/Rule.cs, Samples/DotNetSdk/ObservationValidator/RuleReader.cs, Samples/DotNetSdk/ObservationValidator/ValidationResult.cs, Samples/DotNetSdk/ObservationValidator/ValidationRules.txt, Samples/DotNetSdk/ObservationValidator/Validator.cs, Samples/DotNetSdk/ObservationValidator/packages.config
@schmidt4brains , 
This adds the `ObservationValidator` as an example project of using Aquarius .net SDK to interact with Samples system.
Can you review?
Thanks,
Bill
=> PF-109 Added the feature complete ObservationValidator as an example project

Samples/DotNetSdk/ObservationValidator/ObservationValidator.csproj, Samples/DotNetSdk/ObservationValidator/Program.cs, Samples/DotNetSdk/ObservationValidator/ValidationResult.cs, Samples/DotNetSdk/ObservationValidator/Validator.cs
@schmidt4brains ,
Added a few more checks on null values as per the testing results.
Also let the tool finish validating all fetched observations instead of exiting the whole program when there is an error processing one individual observation.
Can you review?
Thanks,
Bill
=> PF-109 Added null checks and changed to log errors then continue

TimeSeries/PublicApis/SdkExamples/TimeSeriesChangeMonitor/TimeSeriesChangeMonitor.csproj, appveyor.yml
- Don't try to run as 32-bit
- Only start a PR build for SdkExamples
=> Issue-48 Minor tweaks

TimeSeries/PublicApis/SdkExamples/TimeSeriesChangeMonitor/Monitor.cs
Added code to fetch time-series descriptions as quickly as possible, in batches of 400 time-series per request.
This will put the lowest overall DB load on the AQTS system, and will also serve as working code example for others wanting to achieve similar performance when data-warehousing.
=> Issue-48 Fetch time-series description in large batches

TimeSeries/PublicApis/SdkExamples/LocationDeleter/Deleter.cs
@schmidt4brains , could you review? Thanks.
=> Issue-57 Fixed an issue when objects will be deleted on DryRun mode

TimeSeries/SampleFiles/FieldData/Stock/USGS/UsgsHydroMLSample.xml
Changed some parameters and methods so that this example file can be used on a box-stock Time-Series system.
=> Removed USGS-only items

TimeSeries/PublicApis/SdkExamples/LocationDeleter/Deleter.cs
This works around a bug in the Publish API which should just return an empty list in the RatingCurveListServiceResponse. AQ-19706
=> Issue-103 Allow empty rating models to be deleted

TimeSeries/PublicApis/SdkExamples/PointZilla/Context.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/CsvReader.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/PointZilla.csproj, TimeSeries/PublicApis/SdkExamples/PointZilla/Program.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/Readme.md, TimeSeries/PublicApis/SdkExamples/PointZilla/packages.config
The same CSV options can now be used to parse Excel workbooks.
=> Issue-138 - Added Excel worksheet parsing

TimeSeries/PublicApis/SdkExamples/LocationDeleter/Context.cs, TimeSeries/PublicApis/SdkExamples/LocationDeleter/Deleter.cs, TimeSeries/PublicApis/SdkExamples/LocationDeleter/LocationDeleter.csproj, TimeSeries/PublicApis/SdkExamples/LocationDeleter/Program.cs, TimeSeries/PublicApis/SdkExamples/LocationDeleter/Readme.md, TimeSeries/PublicApis/SdkExamples/LocationDeleter/VisitIdentifier.cs, TimeSeries/PublicApis/SdkExamples/LocationDeleter/VisitIdentifierParser.cs
The -Visit=location@date or -Visit=location@dateTime option can be set more than once to delete many specific visits.
=> PF-477 - Added support to delete a specific set of visits

TimeSeries/PublicApis/Python/Readme.md
1) Added a note that authentication requires a credentialed account, not ActiveDirectory or OpenIdConnect
2) Added a PUT example, to modify the HG identifier
=> Issue-158 - Improved python docs and examples

Samples/DotNetSdk/SondeFileImporter/Config.ini, Samples/DotNetSdk/SondeFileImporter/Readme.md
@ChuckSpringer-AI , 
I've made changes in `Readme` and `config.ini` files based on our discussion this morning. 
One thing I want to correct is that `ArchiveWhenFileNumberIsLargerThan` is actually required.
Can you take a look?
Thanks,
Bill
=> PF-577 Modified readme and comments in config.ini

TimeSeries/PublicApis/SdkExamples/SosExporter/Exporter.cs
1) Now there is just a single GetCorrectedData request made per time-series.
This should put the least possible API pressure on AQTS.
2) Only extract to the end of the next ChangesSinceToken value
All the extracted time-series will use the same upper time boundary.
N no matter how long one sync cycle is, all time-series will be extracted to the same end point.
3) Attribute changes force a resync for the time-series
So if someone changes the "SosExportDuration" extended attribute from "5 days" to "6 months", the next export will fetch all 6 months of data.
4) Added a safety limit of a 10K point limit maximum
Added a safety net to limit the exported points to a 10K max (which will still hold 7 days of 1-minute data).
So if someone says "Export the last 20 years of this 1-point-per-minute …
=> PF-540 - Simplified AQTS point extraction logic.

TimeSeries/PublicApis/SdkExamples/SosExporter/Exporter.cs
1) Log the export duration attribute value, or "DefaultExportDurationDays" for each time-series
This will help find time-series which aren't properly configured for export.
2) Only sync points up to the end of the NextChangesSince window
This should lower the likelihood of points in the future forcing a full sensor resync
=> PF-540 - Improved SOS export window logic

TimeSeries/PublicApis/R/ExtremeValueAnalysis/timeseries_client.R, TimeSeries/PublicApis/R/FloodFrequencyAnalysis/timeseries_client.R, TimeSeries/PublicApis/R/FlowDurationCurve/timeseries_client.R, TimeSeries/PublicApis/R/IntensityDurationFrequency/timeseries_client.R, TimeSeries/PublicApis/R/ShinyCorrelator/timeseries_client.R, TimeSeries/PublicApis/R/ShinyFlowDurationCurve/timeseries_client.R, TimeSeries/PublicApis/R/WDTF/timeseries_client.R, TimeSeries/PublicApis/R/WindRose/timeseries_client.R, TimeSeries/PublicApis/R/timeseries_client.R
Handle the scenario where the AQTS report list is completely empty
=> Issue-192 - Bugfix for uploadExternalReports()

Samples/DotNetSdk/LabFileImporter/Context.cs, Samples/DotNetSdk/LabFileImporter/CsvWriter.cs, Samples/DotNetSdk/LabFileImporter/Importer.cs, Samples/DotNetSdk/LabFileImporter/LabFileLoader.cs, Samples/DotNetSdk/LabFileImporter/Program.cs, Samples/DotNetSdk/LabFileImporter/Readme.md
Also started flushing out the Readme
=> PF-764 - Improved validation and error reporting logic

TimeSeries/PublicApis/SdkExamples/TimeSeriesChangeMonitor/Context.cs, TimeSeries/PublicApis/SdkExamples/TimeSeriesChangeMonitor/Monitor.cs, TimeSeries/PublicApis/SdkExamples/TimeSeriesChangeMonitor/Program.cs, TimeSeries/PublicApis/SdkExamples/TimeSeriesChangeMonitor/Readme.md
This will help other intergrations to build on top of change detection
=> PF-799 - Added options to save detected events to CSV and exit

Samples/DotNetSdk/LabFileImporter/Context.cs, Samples/DotNetSdk/LabFileImporter/Importer.cs, Samples/DotNetSdk/LabFileImporter/LabFileLoader.cs, Samples/DotNetSdk/LabFileImporter/MainForm.Designer.cs, Samples/DotNetSdk/LabFileImporter/MainForm.cs, Samples/DotNetSdk/LabFileImporter/Program.cs, Samples/DotNetSdk/LabFileImporter/Readme.md
Allow for the Method and QC Type columns to be aliased.
Also compose the LabSampleMethod from the analysis method ID, name, and context
=> PF-764 - Added Method and QC Type alias support

Samples/DotNetSdk/SamplesObservationExporter/Exporter.cs
1) AnalyticalGroup and ObservedProperty filters are now ORed together.
2) When all named ObservedProperties are contained in the named AnalyticalGroup, just filter based only on the AnalyticalGroups
3) Location and Property filters are now ORed together.
4) If both Location and Property filters are used, require a StartTime or EndTime filter as well
=> PF-821 - Changed the filter combination logic to match EAA's spec

Samples/DotNetSdk/SamplesPlannedSpecimenInstantiator/MainForm.cs
GET /v1/fieldtrips is going to change its response in AQS 2020.6, so rework the algorithm logic to avoid this API.
This will allow GWM ot take the updated tool ahead of the breaking change and remain unaffected.
=> PF-905 - Update the Planned Specimen Instantiator tool to avoid a breaking API change

Samples/DotNetSdk/LabFileImporter/FileUploader.cs, Samples/DotNetSdk/LabFileImporter/ImportClient.cs, Samples/DotNetSdk/LabFileImporter/Importer.cs, Samples/DotNetSdk/LabFileImporter/LabFileImporter.csproj, Samples/DotNetSdk/LabFileImporter/packages.config
Bypass the buggy async SDK methods and use RestSharp instead.
Might need to rethink this later.
=> PF-1039 - Rework the file upload for the LabFileImporter

TimeSeries/PublicApis/SdkExamples/PointZilla/App.config, TimeSeries/PublicApis/SdkExamples/PointZilla/Context.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/CsvWriter.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/DbClient/DbClientBase.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/DbClient/DbClientFactory.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/DbClient/DbType.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/DbClient/IDbClient.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/DbClient/MySqlClient.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/DbClient/OdbcClient.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/DbClient/PostgresDbClient.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/DbClient/SqlServerClient.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/Field.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/PointReaders/CsvReader.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/PointReaders/DbPointsReader.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/PointReaders/ExternalPointsReader.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/PointReaders/IPointReader.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/PointReaders/PointReaderBase.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/PointZilla.csproj, TimeSeries/PublicApis/SdkExamples/PointZilla/PointsAppender.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/Program.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/Readme.md, TimeSeries/PublicApis/SdkExamples/PointZilla/packages.config
Support SqlServer, mySql, and Postgres queries natively, plus ODBC as a catch all.
Also added either named columns or column index fields for CSV, Excel, and DB readers.
=> PF-1047 - Added DB reader support to PointZilla

TimeSeries/PublicApis/SdkExamples/SosExporter/docker-proxy/Readme.md, TimeSeries/PublicApis/SdkExamples/SosExporter/docker-proxy/docker-compose/docker-compose.yml
Added documentation for how to expect AQTS location and series data to be mapped into SOS OGC data.
=> Update to aq_pr.4 release of the SOS-proxy

TimeSeries/PublicApis/SdkExamples/PointZilla/PointsAppender.cs
Now you can just queue points without waiting for the append to complete, just like most telemetry systems.
=> PF-1244 - Fixed the broken -Wait=false logic in PointZilla

Samples/DotNetSdk/ObservationReportExporter/Program.cs
=> PF-1365 - Oops. Fixed a double-launch problem for ObservationReportExporter

TimeSeries/PublicApis/SdkExamples/LocationDeleter/Deleter.cs
The list of locations needed to be trimmed of duplicates.
=> PF-1387 - Fix the visit summary when specific visits are targeted
