TimeSeries/PublicApis/R/Readme.md, TimeSeries/PublicApis/R/timeseries_client.R
@GordPollock-AI Can you have a look? This just adds a bit of version-checking to the R wrapper, to make the failure a bit more obvious if someone tries to run this against a pre-17.2 build of AQTS.
1) Added version checking for the server version
2) Fail if the server is not running AQTS 17.2 when asking for time-aligned data
3) Updated the readme to note the 17.2 requirement
=> PF-35 Some R wrapper updates

TimeSeries/PublicApis/FieldDataPlugins/ExampleFieldDataPlugins.sln, TimeSeries/PublicApis/FieldDataPlugins/ManualGaugingPlugin/CreatorBase.cs, TimeSeries/PublicApis/FieldDataPlugins/ManualGaugingPlugin/DischargeActivityCreator.cs, TimeSeries/PublicApis/FieldDataPlugins/ManualGaugingPlugin/DoubleHelper.cs, TimeSeries/PublicApis/FieldDataPlugins/ManualGaugingPlugin/FieldDataResultsGenerator.cs, TimeSeries/PublicApis/FieldDataPlugins/ManualGaugingPlugin/FileData/DischargeActivityRecord.cs, TimeSeries/PublicApis/FieldDataPlugins/ManualGaugingPlugin/FileData/FieldVisitRecord.cs, TimeSeries/PublicApis/FieldDataPlugins/ManualGaugingPlugin/FileData/ManualGaugingRecord.cs, TimeSeries/PublicApis/FieldDataPlugins/ManualGaugingPlugin/FileData/Meter.cs, TimeSeries/PublicApis/FieldDataPlugins/ManualGaugingPlugin/FileData/MeterEquation.cs, TimeSeries/PublicApis/FieldDataPlugins/ManualGaugingPlugin/FileData/VelocityObservation.cs, TimeSeries/PublicApis/FieldDataPlugins/ManualGaugingPlugin/FileReader.cs, TimeSeries/PublicApis/FieldDataPlugins/ManualGaugingPlugin/ManualGaugingCreator.cs, TimeSeries/PublicApis/FieldDataPlugins/ManualGaugingPlugin/ManualGaugingPlugin.cs, TimeSeries/PublicApis/FieldDataPlugins/ManualGaugingPlugin/ManualGaugingPlugin.csproj, TimeSeries/PublicApis/FieldDataPlugins/ManualGaugingPlugin/ManualGaugingResultSummary.cs, TimeSeries/PublicApis/FieldDataPlugins/ManualGaugingPlugin/MeterCalibrationCreator.cs, TimeSeries/PublicApis/FieldDataPlugins/ManualGaugingPlugin/MetricUnitSystem.cs, TimeSeries/PublicApis/FieldDataPlugins/ManualGaugingPlugin/Properties/AssemblyInfo.cs, TimeSeries/PublicApis/FieldDataPlugins/ManualGaugingPlugin/VerticalsCreator.cs, TimeSeries/PublicApis/FieldDataPlugins/Readme.md, TimeSeries/PublicApis/FieldDataPlugins/StageDischargePlugin/DischargeActivityCreator.cs, TimeSeries/PublicApis/FieldDataPlugins/StageDischargePlugin/FieldDataResultsGenerator.cs, TimeSeries/PublicApis/FieldDataPlugins/StageDischargePlugin/FileData/DischargeActivityRecord.cs, TimeSeries/PublicApis/FieldDataPlugins/StageDischargePlugin/FileData/FieldVisitRecord.cs, TimeSeries/PublicApis/FieldDataPlugins/StageDischargePlugin/FileReader.cs, TimeSeries/PublicApis/FieldDataPlugins/StageDischargePlugin/MetricUnitSystem.cs, TimeSeries/PublicApis/FieldDataPlugins/StageDischargePlugin/Properties/AssemblyInfo.cs, TimeSeries/PublicApis/FieldDataPlugins/StageDischargePlugin/StageDischargePlugin.cs, TimeSeries/PublicApis/FieldDataPlugins/StageDischargePlugin/StageDischargePlugin.csproj
Created a solution containing two example field data plugins to demonstrate how to write a plugin for the field data plugin framework.  The plugins compile, but they do not import data because it is missing functionality to read and parse a field data file.  This functionality is stubbed out in FileReader.cs.
=> AQ-22322 Add ExampleFieldDataPlugins

TimeSeries/PublicApis/FieldDataPlugins/PluginTester/AppendedResults.cs, TimeSeries/PublicApis/FieldDataPlugins/PluginTester/FieldDataResultsAppender.cs, TimeSeries/PublicApis/FieldDataPlugins/PluginTester/PluginTester.csproj, TimeSeries/PublicApis/FieldDataPlugins/PluginTester/Program.cs
This will help us know which versions were used to generate the JSON.
=> PF-64 Store the plugin and framework assembly qualified name in the JSON result

TimeSeries/PublicApis/FieldDataPlugins/PluginTester/PluginTester.csproj, TimeSeries/PublicApis/FieldDataPlugins/PluginTester/Program.cs
This will prevent a plugin developer from successfully casting the Stream parameter to a FileStream subclass when trying to get the uploaded filename.
This change fixes a bug where a plugin would work within the test hardness but fail at runtime.
=> PF-70 The plugin tester now uses an in-memory stream

TimeSeries/PublicApis/FieldDataPlugins/PluginTester/Program.cs
This more closely simulates the environment of the real plugin framework.
=> PF-70 The field data plugin test now uses a MemoryStream instead of a FileStream

TimeSeries/PublicApis/SdkExamples/SdkExamples.sln, TimeSeries/PublicApis/SdkExamples/TimeSeriesChangeMonitor/Context.cs, TimeSeries/PublicApis/SdkExamples/TimeSeriesChangeMonitor/Monitor.cs, TimeSeries/PublicApis/SdkExamples/TimeSeriesChangeMonitor/Program.cs, TimeSeries/PublicApis/SdkExamples/TimeSeriesChangeMonitor/Readme.md
- Improved the Readme
- Added `AllowQuickPolling` and enforce the 5-minute minimum polling interval by default
- Set the `Parameter` and `Publish` filters when all monitored time-series share the same values
=> Issue-48 Minor TimeSeriesChangeMonitor improvements

TimeSeries/PublicApis/SdkExamples/LocationDeleter/Deleter.cs
This avoids a nasty exception, since it just isn't possible from any API.
=> Issue-63 Skip deletion of external time-series

TimeSeries/PublicApis/SdkExamples/PointZilla/Context.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/PointsAppender.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/Program.cs
This allows PointZilla to break up very large sets of points and send it in sequential batches. In my testing, I found a batch size of 500k a little easier to test, so I am not quite meeting the requirement of Issue #73...
=> Issue-73 Batch large appends

TimeSeries/PublicApis/SdkExamples/LocationDeleter/Deleter.cs, TimeSeries/PublicApis/SdkExamples/LocationDeleter/PrivateApis.cs
If a time-series delete request fails because the time-series has locked approval regions, prompt the user if they really want to delete the time-series anyways.
If confirmed, unlock the entire time-series by setting it to the lowest approval level.
Then try deleting it again.
=> Issue-91 Allow a time-series with locked approval regions to be deleted.

TimeSeries/PublicApis/Python/timeseries_client.py
This PR provides the ability to connect to Aquarius servers which do not have properly verified SSL certificates by passing the ``verify=False`` kwarg through to the requests package.
In particular the provisioning API didn't seem to work without HTTPS (didn't look closely at other means of getting around it).
=> Fix #111 - pass through verify kwarg to requests

TimeSeries/PublicApis/Python/setup.py
This PR allows the Python wrapper to be installed as a Python package.
At the moment it installs the ``timeseries_client.py`` file as a module ``timeseries_client``. This could be changed to a proper package in a folder with an ``__init__.py`` file, but that's probably not necessary at the moment.
Example installation after cloning the repo:
```cmd
(temp) C:\Program Files (x86)\MISC\kent>pip install -e Examples\TimeSeries\PublicApis\Python
Looking in indexes: https://pypi.org/simple, http://envtelem04:8090/simple/
Obtaining file:///C:/Program%20Files%20%28x86%29/MISC/kent/Examples/TimeSeries/PublicApis/Python
Collecting requests (from aquarius-timeseries-client==0.1)
Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/reque …
```
=> Make Python wrapper a proper package (Add setup.py file)

TimeSeries/PublicApis/SdkExamples/WaterWatchPreProcessor/Exporter.cs, TimeSeries/PublicApis/SdkExamples/WaterWatchPreProcessor/log4net.config
Don't log to StandardOutput at all (leave that stream alone, for pure preprocessor output)
Log WARN+ to StandardError
Log INFO+ to the file
Log measurement summary per sensor and in total.
=> Issue-115 - Improved logging of the preprocessor

TimeSeries/PublicApis/SdkExamples/LocationDeleter/Deleter.cs
Some location identifiers are giving the delete-by-Identifier request some troubles.
When that server bug is fixed, try one of the other private APIs to keep going.
=> Issue-132 - Try an alternative API if the main location delete API fails

TimeSeries/PublicApis/SdkExamples/SosExporter/SosClient.cs
Add a useful UserAgent header into the requests, so that web server logs can be filtered more easily
=> Issue-135 SosExporter tweaks

TimeSeries/PublicApis/SdkExamples/PointZilla/CsvReader.cs
Now, only the text "Gap" (case-insensitive) is accepted.NodaTime.
A text value of "2" is now treated as a normal numeric value of 2.0.
=> Issue-140 - Fixed the parsing of "Gap" values from CSV rows

TimeSeries/PublicApis/SdkExamples/PointZilla/CsvReader.cs
When the -CsvDateTimeFormat format isn't UTC, add the -UtcOffset to all the timestamps
=> PF-538 - Support reading CSV timestamps without a UTC offset

TimeSeries/PublicApis/SdkExamples/TotalDischargeExternalProcessor/EventIntervalDetector.cs, TimeSeries/PublicApis/SdkExamples/TotalDischargeExternalProcessor/ExternalProcessor.cs
Treat a falling signal like a flat signal.
We only consider an event to start once the signal starts rising.
Also add any required extended attribute values when creating a time-series.
=> PF-580 - Fix the event interval detection logic

appveyor.yml
@DougSchmidt-AI , just realized the names used in `appveyor.yml` were still the old names for SondeFileImporter. Fixed. 
Can you review and merge if things look good?
Bill
=> PF-577 Corrected names in appveyor.yml for SondeFileImporter

TimeSeries/PublicApis/SdkExamples/SosExporter/Context.cs, TimeSeries/PublicApis/SdkExamples/SosExporter/Exporter.cs, TimeSeries/PublicApis/SdkExamples/SosExporter/Program.cs, TimeSeries/PublicApis/SdkExamples/SosExporter/Readme.md
This defaults to 10K points, which is good for 7 days of 1-minute data.
=> PF-540 - Added the configurable MaximumPointsPerSensor

TimeSeries/PublicApis/SdkExamples/SosExporter/Exporter.cs
Many stats calculate a little bit into the future. But the QueryTo value must be >= QueryFrom
=> PF-540 - Don't filter the retrieved data to the start of sync interval

TimeSeries/PublicApis/SdkExamples/SosExporter/SyncStatus.cs
Use a dash instead of a period in the configuration-specific settings.
=> Issue-186 - Global setting keys no longer support a period

TimeSeries/PublicApis/SdkExamples/PointZilla/CsvReader.cs
It was working for Excel files, but not plain CSV files.
=> PF-763 - Fix for CsvSkipRows option

Samples/DotNetSdk/SamplesObservationExporter/Exporter.cs, Samples/DotNetSdk/SamplesObservationExporter/Program.cs, Samples/DotNetSdk/SamplesObservationExporter/Readme.md, Samples/DotNetSdk/SamplesObservationExporter/log4net.config, Samples/DotNetSdk/SamplesPlannedSpecimenInstantiator/Readme.md
1) Use the singular form of the ID name filters
This will allow for an observed property Id containing a comma, which is common enough.
-ObservedPropertyId="Algae, blue-green density"
2) Made the log4net configuration more sane
3) Improved the readme links a bit
=> PF-766 - ObservationExporter fixes

TimeSeries/PublicApis/Python/Readme.md, TimeSeries/PublicApis/Python/WindRose/AQTS-WindRose.py, TimeSeries/PublicApis/Python/WindRose/timeseries_client.py, TimeSeries/PublicApis/Python/timeseries_client.py
1) Changed the session methods to implicitly call response.json()
This breaking makes the results much more fluent.
2) Improved the send_batch_requests() helper method
Now it will lookup the metadata route and be a bit more robust if the server-side operation name ever changes.
=> PF-782 - Eliminated the .json() ceremony around each API request

Samples/DotNetSdk/SamplesObservationExporter/Exporter.cs
The wrong name was being used to find observed properties within analytical groups. This is now fixed.
=> PF-766 - Fixed the sort ordering

TimeSeries/PublicApis/SdkExamples/SosExporter/docker/docker-compose/docker-compose.yml
The SOS Exporter only works with v4.4.x of 52North's SOS server. Now that 52North has released v5.x as the 'latest' version, things have broken.
Yay! Standards are great!
=> Updated SOSExporter's docker config to use v4.4.x of SOS

Samples/DotNetSdk/LabFileImporter/LabFileLoader.cs
So the input spreadsheet can contain "> 10,000" but the MRL value imported will be "10000".
=> PF-909 - Remove any commas from the Minimum Result Limit

Samples/DotNetSdk/LabFileImporter/Context.cs, Samples/DotNetSdk/LabFileImporter/LabFileLoader.cs, Samples/DotNetSdk/LabFileImporter/MainForm.Designer.cs, Samples/DotNetSdk/LabFileImporter/MainForm.cs, Samples/DotNetSdk/LabFileImporter/Program.cs
This will allow for -REPLICATE or -SPIKE to be added to the activity name as requested by SCC.
=> PF-955 - Added configurable ActivityNameSuffic for QcAliases

TimeSeries/PublicApis/SdkExamples/PointZilla/Program.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/Readme.md
This allows `-CsvDelimiter=%20` for files delimited with a space and `-CsvDelimiter=%09` for files delimited with a tab
=> PF-1084 - PointZilla - Support UrlEncoding of CsvDelimiter option

TimeSeries/PublicApis/SdkExamples/SosExporter/docker-proxy/Readme.md, TimeSeries/PublicApis/SdkExamples/SosExporter/docker-proxy/docker-compose/docker-compose.yml
Also hid the tomcat from external consumption. Now all external requests must go through the nginx reverse proxy.
=> Update docker-proxy reference to the latest tag

TimeSeries/PublicApis/Python/Readme.md, TimeSeries/PublicApis/Python/timeseries_client.py
Expose more of the content from AQTS and AQSamples error responses.
This should help make the source of errors a bit more obvious to the clients.
=> PF-1044 - Improved the format of raised HTTP errors

Samples/DotNetSdk/LabFileImporter/LabFileImporter.csproj, Samples/DotNetSdk/LabFileImporter/packages.config, Samples/DotNetSdk/NWFWMD-LabFileImporter/NWFWMD-LabFileImporter.csproj, Samples/DotNetSdk/NWFWMD-LabFileImporter/packages.config, Samples/DotNetSdk/ObservationReportExporter/Exporter.cs, Samples/DotNetSdk/ObservationReportExporter/ObservationReportExporter.csproj, Samples/DotNetSdk/ObservationReportExporter/Program.cs, Samples/DotNetSdk/ObservationReportExporter/Readme.md, Samples/DotNetSdk/ObservationReportExporter/SingleInstanceGuard.cs
1) Ensure only one instance-per-config runs per computer.
This allows you to schedule a configuration on a 3-hour schedule which sometimes takes 4 hours to complete, and avoid kicking off another cycle before the first one is actually done.
2) Log the number of exported observations per location
3) Documented the basic workflow and scheduling options
=> PF-1365 - Minor tweaks

TimeSeries/PublicApis/SdkExamples/PointZilla/Context.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/Field.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/Formats.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/PointReaders/CsvReader.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/PointReaders/PointReaderBase.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/Program.cs, TimeSeries/PublicApis/SdkExamples/PointZilla/Readme.md
1) Added -CsvSkipRowsAfterHeader= option (to skip the dummy line after the header in NWIS data)
2) Added regex field matching support
The NWIS data columns have a name like "1234_00060", where 1234 is the timeseries ID and 00060 is the parameter code.
Allow field names to be surround by forward slashes to indicate a regular express match.
"/_00060/" will match the first column that ends with the 00060 parameter code for discharge.
"/_00060/#2" will match the 2nd discharge parameter column.
3) Added the -CsvFormat="NWIS" option
This will also populate USGS timezone aliases.
=> PF-1417 - Added more support for NWIS text files

Samples/DotNetSdk/ObservationReportExporter/Exporter.cs, Samples/DotNetSdk/ObservationReportExporter/ExtraApis/TimeSeries/HackTags.cs, Samples/DotNetSdk/ObservationReportExporter/ObservationReportExporter.csproj
AQTS 2021.2 has Tag.ValueType.Text but the SDK expects Tag.ValueTypeString
Added some version-specific API logic
=> PF-1421 - ObservationReportExporter now works with AQTS 2021.2
